name: todo-backend

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend
    environment:
      - PORT=5000
      - NODE_ENV=production
    ports:
      - "5000:5000"
    restart: unless-stopped
